<a href="https://colab.research.google.com/github/GoradiaNishant/DSML/blob/main/nltk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##NLTK

In [ ]:
#### Reading the dataset

#csv, tsv
#### Data Pre-processing - Data Cleaning
import pandas as pd
import re
import nltk
from nltk.stem.porter import PorterStemmer
nltk.download('stopwords')
from nltk.corpus import stopwords

dataset = pd.read_csv('/content/Restaurant_Reviews.tsv',delimiter='\t', quoting=3)
review1 = re.sub('[^a-zA-Z]',' ', dataset['Review'][0])
review1 = review1.lower()
review1 = review1.split()

ps = PorterStemmer()

review1 = [ps.stem(word) for word in review1 if not word in set(stopwords.words('english'))]
review1 = ' '.join(review1)

### Read dataset
### Data Cleaning - re
### lowercase -
### split
### stopwords
### PorterStemmer
### countVectorizer - Sparse matrix - Bag of Word Model
### classification - ML

new_dataset = []
for i in range(0,1000):
    review = re.sub('[^a-zA-Z]',' ', dataset['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    new_dataset.append(review)
    


####  Name related dataset - >95000

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)
x = cv.fit_transform(new_dataset).toarray()


y = dataset.iloc[:,1].values

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)



from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(x_train,y_train)
y_pred = model.predict(x_test)


#### 1500 - 3 words - 3 non zero values - 1497 zero

### To hold only non zero values - we can take help of variation of 
### original sparse matrix

### CSR matrix - Compressed sparse Row

import numpy as np
from scipy.sparse import csr_matrix
arr = np.array([[0,0,0],
                [8,0,0],
                [0,5,4],
                [0,0,0],
                [0,0,7]])

demo = csr_matrix(arr)

print(demo.data)
print(demo.indices)
print(demo.indptr)


# 100 * 100 = 10000
# 50 - non zero - data
# 50 - indices
# 100+1 = 101 - indptr
# total - 201

# [8 5 4 7] - data
# [0 1 2 2] - indices / column
# [0 0 1 3 3 4] - indptr - n rows - n+1 values - 
# ## for ith row - find difference between i and i+1


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[8 5 4 7]
[0 1 2 2]
[0 0 1 3 3 4]
